### ISSUE TITLE
Data outside of sections being cleared

### ISSUE THREAD

**Issue by Perska** [SBS-chatJS/sbs-chatjs.github.io#3]
When you use /loadplugin, /unloadplugin or any plugin that accesses the chatJS, it clears the entire file. The "sections" are returned though.
I had non-plugin commands which were removed because of this. (they were above the ChatJS plugin bootstrap.)

Can't you make it so it accesses only the ChatJS plugin portion which was the case on 1.x?
You know, the //START BOOT and //END BOOT comments in the bootstrap.

**Comment by ShadowC-X-11** [comment]
No, something like the old system would break the new system. Let me explain.

See, the old system worked by doing a lot of funky RegExp stuff. However, the new system uses sections comments. How this new system works is it has to parse through the chatJS and read everything, then convert it to an object I can modify. This would not work properly with RegExp, so that's the problem.

However, there's another solution: the // SECTION PREBOOT proposal. This would be data that's run BEFORE the bootstrap. This is alongside the // SECTION GLOBALDATA proposal, which would allow plugins to access an area to store data, but this would be after the rest of the chatJS sections, and not actually run (probably as a multiline comment). This would make the system fully configurable.

I'm running this by the other devs and then we'll get this sorted. If I have to, I'll create another virtual section for code before the sections. However, that'd make the section system more complicated then it already is, and preboot/globaldata would only require a bootstrap update (a special one that'll clear everything except // SECTION LOADS inside chatJS).

**Comment by ShadowC-X-11** [comment]
Okay, this issue has been solved by a few pull requests by @Trinitro21.
